dist: xenial

jobs:
  include:
    - stage: build
      name: "build image"
      if: (tag IS blank)
      sudo: required
      services:
        - docker
      script:
      - docker build -t hackerh/wakeonlan:latest .

    - stage: build
      name: "push latest image"
      if: (branch = master AND NOT type = pull_request)
      sudo: required
      services:
        - docker
      script:
      - docker build -t hackerh/wakeonlan:latest .
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - docker push hackerh/wakeonlan:latest

    - stage: build
      name: "push tagged image"
      if: (tag IS present)
      sudo: required
      services:
        - docker
      script:
      - docker build -t hackerh/wakeonlan:"${TRAVIS_TAG}" .
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - docker push hackerh/wakeonlan:"${TRAVIS_TAG}"
